import { Mission } from '../types/mission';

export const DEFAULT_MISSIONS: Omit<Mission, 'id' | 'createdAt' | 'updatedAt'>[] = [
  // DAILY MISSIONS
  {
    title: 'Login Diario',
    description: 'Ingresa a la aplicación hoy.',
    type: 'daily',
    actionType: 'daily_login',
    targetValue: 1,
    rewardType: 'xp',
    rewardAmount: 20,
    isRepeatable: true,
    maxClaimsPerUser: 1,
    status: 'active',
    sortOrder: 1,
  },
  {
    title: 'Únete a una sala',
    description: 'Entra a cualquier sala de voz para interactuar.',
    type: 'daily',
    actionType: 'join_room',
    targetValue: 1,
    rewardType: 'xp',
    rewardAmount: 30,
    isRepeatable: true,
    maxClaimsPerUser: 1,
    status: 'active',
    sortOrder: 2,
  },
  {
    title: 'Mira lives 10 minutos',
    description: 'Disfruta de transmisiones en vivo durante un total de 10 minutos.',
    type: 'daily',
    actionType: 'watch_live_minutes',
    targetValue: 10,
    rewardType: 'xp',
    rewardAmount: 50,
    isRepeatable: true,
    maxClaimsPerUser: 1,
    status: 'active',
    sortOrder: 3,
  },
  {
    title: 'Envía 5 mensajes',
    description: 'Envía al menos 5 mensajes en chats públicos de salas o lives.',
    type: 'daily',
    actionType: 'send_message',
    targetValue: 5,
    rewardType: 'xp',
    rewardAmount: 25,
    isRepeatable: true,
    maxClaimsPerUser: 1,
    status: 'active',
    sortOrder: 4,
  },
  {
    title: 'Juega una partida',
    description: 'Juega a cualquier juego casual (Trivia, PPT o Dados).',
    type: 'daily',
    actionType: 'play_game',
    targetValue: 1,
    rewardType: 'xp',
    rewardAmount: 40,
    isRepeatable: true,
    maxClaimsPerUser: 1,
    status: 'active',
    sortOrder: 5,
  },
  {
    title: 'Sigue a un usuario',
    description: 'Sigue a un nuevo creador de contenido o amigo.',
    type: 'daily',
    actionType: 'follow_user',
    targetValue: 1,
    rewardType: 'xp',
    rewardAmount: 30,
    isRepeatable: true,
    maxClaimsPerUser: 1,
    status: 'active',
    sortOrder: 6,
  },

  // WEEKLY MISSIONS
  {
    title: 'Espectador Fiel',
    description: 'Mira 120 minutos de transmisiones en vivo durante la semana.',
    type: 'weekly',
    actionType: 'watch_live_minutes',
    targetValue: 120,
    rewardType: 'xp',
    rewardAmount: 300,
    isRepeatable: true,
    maxClaimsPerUser: 1,
    status: 'active',
    sortOrder: 10,
  },
  {
    title: 'Gamer Semanal',
    description: 'Juega 10 partidas de juegos casuales esta semana.',
    type: 'weekly',
    actionType: 'play_game',
    targetValue: 10,
    rewardType: 'xp',
    rewardAmount: 250,
    isRepeatable: true,
    maxClaimsPerUser: 1,
    status: 'active',
    sortOrder: 11,
  },
  {
    title: 'Generosidad Semanal',
    description: 'Envía 3 regalos usando diamantes.',
    type: 'weekly',
    actionType: 'send_gift',
    targetValue: 3,
    rewardType: 'gift_ticket',
    rewardAmount: 1,
    isRepeatable: true,
    maxClaimsPerUser: 1,
    status: 'active',
    sortOrder: 12,
  },
  {
    title: 'Socializador',
    description: 'Participa y únete a salas 5 veces diferentes esta semana.',
    type: 'weekly',
    actionType: 'join_room',
    targetValue: 5,
    rewardType: 'xp',
    rewardAmount: 200,
    isRepeatable: true,
    maxClaimsPerUser: 1,
    status: 'active',
    sortOrder: 13,
  },

  // HOST MISSIONS
  {
    title: 'Transmisión Diaria',
    description: 'Transmite en vivo al menos 60 minutos.',
    type: 'host',
    actionType: 'host_live_minutes',
    targetValue: 60,
    rewardType: 'xp',
    rewardAmount: 100,
    isRepeatable: true,
    maxClaimsPerUser: 1,
    requiresHost: true,
    status: 'active',
    sortOrder: 20,
  },
  {
    title: 'Creador de Comunidad',
    description: 'Crea tu propia sala activa.',
    type: 'host',
    actionType: 'create_room',
    targetValue: 1,
    rewardType: 'xp',
    rewardAmount: 80,
    isRepeatable: true,
    maxClaimsPerUser: 1,
    requiresHost: true,
    status: 'active',
    sortOrder: 21,
  },
  {
    title: 'Imán de Regalos',
    description: 'Recibe regalos de al menos 5 usuarios diferentes.',
    type: 'host',
    actionType: 'receive_gift',
    targetValue: 5,
    rewardType: 'event_points',
    rewardAmount: 100,
    isRepeatable: true,
    maxClaimsPerUser: 1,
    requiresHost: true,
    status: 'active',
    sortOrder: 22,
  },
];
