import { DiamondPackage } from '../types/wallet';

export const DIAMOND_PACKAGES: Omit<DiamondPackage, 'createdAt' | 'updatedAt'>[] = [
  {
    id: 'diamonds_100',
    title: '100 Diamantes',
    description: 'Paquete inicial de diamantes',
    diamonds: 100,
    bonusDiamonds: 0,
    totalDiamonds: 100,
    priceUsd: 0.99,
    googlePlayProductId: 'diamonds_100',
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'diamonds_550',
    title: '550 Diamantes',
    description: '50 diamantes de regalo',
    diamonds: 500,
    bonusDiamonds: 50,
    totalDiamonds: 550,
    priceUsd: 4.99,
    googlePlayProductId: 'diamonds_550',
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'diamonds_1200',
    title: '1200 Diamantes',
    description: '200 diamantes de regalo',
    diamonds: 1000,
    bonusDiamonds: 200,
    totalDiamonds: 1200,
    priceUsd: 9.99,
    googlePlayProductId: 'diamonds_1200',
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'diamonds_2500',
    title: '2500 Diamantes',
    description: '300 diamantes de regalo',
    diamonds: 2200,
    bonusDiamonds: 300,
    totalDiamonds: 2500,
    priceUsd: 19.99,
    googlePlayProductId: 'diamonds_2500',
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 'diamonds_7000',
    title: '7000 Diamantes',
    description: '1000 diamantes de regalo',
    diamonds: 6000,
    bonusDiamonds: 1000,
    totalDiamonds: 7000,
    priceUsd: 49.99,
    googlePlayProductId: 'diamonds_7000',
    isActive: true,
    sortOrder: 5,
  },
  {
    id: 'diamonds_15000',
    title: '15000 Diamantes',
    description: '3000 diamantes de regalo (Mejor Valor)',
    diamonds: 12000,
    bonusDiamonds: 3000,
    totalDiamonds: 15000,
    priceUsd: 99.99,
    googlePlayProductId: 'diamonds_15000',
    isActive: true,
    sortOrder: 6,
  },
];
