export * from './navigationTypes';

export const AUTH_ROUTES = {
  LOGIN: 'Login' as const,
  REGISTER: 'Register' as const,
  FORGOT_PASSWORD: 'ForgotPassword' as const,
};

export const SETUP_ROUTES = {
  PROFILE_SETUP: 'ProfileSetup' as const,
};

export const TAB_ROUTES = {
  HOME: 'HomeTab' as const,
  ROOMS: 'RoomsTab' as const,
  LIVES: 'LivesTab' as const,
  GAMES: 'GamesTab' as const,
  PROFILE: 'ProfileTab' as const,
};

export const MAIN_ROUTES = {
  MAIN_TABS: 'MainTabs' as const,
  NOTIFICATIONS: 'Notifications' as const,
  WALLET: 'Wallet' as const,
  RANKINGS: 'Rankings' as const,
  EVENTS: 'Events' as const,
  SEARCH: 'Search' as const,
  ROOM_DETAILS: 'RoomDetails' as const,
  CREATE_ROOM: 'CreateRoom' as const,
  LIVE_DETAILS: 'LiveDetails' as const,
  START_LIVE: 'StartLive' as const,
  GAME_DETAILS: 'GameDetails' as const,
  GAME_SESSION: 'GameSession' as const,
  GAME_INVITES: 'GameInvites' as const,

  EDIT_PROFILE: 'EditProfile' as const,
  PUBLIC_PROFILE: 'PublicProfile' as const,
  SETTINGS: 'Settings' as const,

  HOST_DASHBOARD: 'HostDashboard' as const,
  HOST_APPLICATION: 'HostApplication' as const,
  HOST_RULES: 'HostRules' as const,
  HOST_EARNINGS: 'HostEarnings' as const,
  HOST_ACTIVITY: 'HostActivity' as const,
  HOST_ANALYTICS: 'HostAnalytics' as const,
  AGENCY_ANALYTICS: 'AgencyAnalytics' as const,

  HOST_PAYOUTS: 'HostPayouts' as const,
  REQUEST_PAYOUT: 'RequestPayout' as const,
  PAYOUT_METHODS: 'PayoutMethods' as const,
  ADD_PAYOUT_METHOD: 'AddPayoutMethod' as const,
  PAYOUT_DETAILS: 'PayoutDetails' as const,
  MISSIONS: 'Missions' as const,
  NOTIFICATION_SETTINGS: 'NotificationSettings' as const,
  SOCIAL_LIST: 'SocialList' as const,
  SOCIAL_FEED: 'SocialFeed' as const,
  PRIVACY_SETTINGS: 'PrivacySettings' as const,
  PRIVATE_CONVERSATIONS: 'PrivateConversations' as const,
  PRIVATE_CHAT: 'PrivateChat' as const,
  MESSAGE_REQUESTS: 'MessageRequests' as const,
  PRIVATE_CHAT_SETTINGS: 'PrivateChatSettings' as const,
  KARAOKE_HOME: 'KaraokeHome' as const,
  KARAOKE_SONG_SEARCH: 'KaraokeSongSearch' as const,
  KARAOKE_QUEUE: 'KaraokeQueue' as const,
  KARAOKE_PERFORMANCE: 'KaraokePerformance' as const,
  KARAOKE_BATTLE: 'KaraokeBattle' as const,
  MY_KARAOKE_HISTORY: 'MyKaraokeHistory' as const,
  PK_HISTORY: 'PkHistory' as const,
  PK_RESULTS: 'PkResults' as const,
  PK_DISCOVERY: 'PkDiscovery' as const,
  CLUBS_HOME: 'ClubsHome' as const,
  CLUB_DETAILS: 'ClubDetails' as const,
  FAVORITE_HOSTS: 'FavoriteHosts' as const,
  CLIPS_FEED: 'ClipsFeed' as const,
  MY_SUBSCRIPTIONS: 'MySubscriptions' as const,
  REFERRAL_DASHBOARD: 'ReferralDashboard' as const,
  ADMIN_CONTROL_CENTER: 'AdminControlCenter' as const,
  SOCIAL_FEED: 'SocialFeed' as const,
  CREATOR_STUDIO: 'CreatorStudio' as const,
  MUSIC_ADMIN_CENTER: 'MusicAdminCenter' as const,
  SAFETY_CENTER: 'SafetyCenter' as const,
  NOTIFICATION_CENTER: 'NotificationCenter' as const,
  HELP_CENTER: 'HelpCenter' as const,
  ADMIN_REGIONAL_CENTER: 'AdminRegionalCenter' as const,
  ADMIN_MONETIZATION_CENTER: 'AdminMonetizationCenter' as const,
  ADMIN_CREATOR_CENTER: 'AdminCreatorCenter' as const,
  ADMIN_DISCOVERY_CENTER: 'AdminDiscoveryCenter' as const,
  ADMIN_GAMIFICATION_CENTER: 'AdminGamificationCenter' as const,
  ADMIN_SAFETY_CENTER: 'AdminSafetyCenter' as const,
  ADMIN_SUPER_CENTER: 'AdminSuperCenter' as const,
  ADMIN_COMPLIANCE_CENTER: 'AdminComplianceCenter' as const,
  ADMIN_PRODUCTION_CENTER: 'AdminProductionCenter' as const,
  ADMIN_PERFORMANCE_CENTER: 'AdminPerformanceCenter' as const,
  ADMIN_QA_CENTER: 'AdminQACenter' as const,
  ADMIN_LAUNCH_CENTER: 'AdminLaunchCenter' as const,
  ADMIN_GROWTH_CENTER: 'AdminGrowthCenter' as const,
  ADMIN_CFO_CENTER: 'AdminCFOCenter' as const,
  ADMIN_EXPANSION_CENTER: 'AdminExpansionCenter' as const,
  ADMIN_AI_CENTER: 'AdminAICenter' as const,
  CREATOR_STUDIO_PRO: 'CreatorStudioPro' as const,
  ADMIN_MONETIZATION_CENTER: 'AdminMonetizationCenter' as const,
  ADMIN_LIVE_ENGAGEMENT: 'AdminLiveEngagement' as const,
  ADMIN_VIRAL_GROWTH_CENTER: 'AdminViralGrowthCenter' as const,
  ADMIN_TRUST_SAFETY: 'AdminTrustSafety' as const,
  ADMIN_COMMAND_CENTER: 'AdminCommandCenter' as const,
  ADMIN_INFRASTRUCTURE_CENTER: 'AdminInfrastructureCenter' as const,
  ADMIN_DATA_INTELLIGENCE: 'AdminDataIntelligence' as const,
  CREATOR_STUDIO_PRO: 'CreatorStudioPro' as const,
  ADMIN_SUBSCRIPTION_CENTER: 'AdminSubscriptionCenter' as const,
  ADMIN_OFFER_CENTER: 'AdminOfferCenter' as const,
  ADMIN_GROWTH_ACQUISITION: 'AdminGrowthAcquisition' as const,
  ADMIN_TRUST_SAFETY_2: 'AdminTrustSafety2' as const,
  ADMIN_GLOBALIZATION_CENTER: 'AdminGlobalizationCenter' as const,
  ADMIN_INFRASTRUCTURE_2: 'AdminInfrastructure2' as const,
  ADMIN_COMPLIANCE_LAUNCH: 'AdminComplianceLaunch' as const,
  ADMIN_UX_CONVERSION: 'AdminUxConversion' as const,
  ADMIN_MASTER_AUDIT: 'AdminMasterAudit' as const,
  ADMIN_LIVE_OPERATIONS: 'AdminLiveOperations' as const,
  ADMIN_CREATOR_ECONOMY_2: 'AdminCreatorEconomy2' as const,
  AGENCY_APPLICATION: 'AgencyApplication' as const,
  AGENCY_DASHBOARD: 'AgencyDashboard' as const,
  AGENCY_HOSTS: 'AgencyHosts' as const,
  VERIFICATION_START: 'VerificationStart' as const,
  VERIFICATION_FORM: 'VerificationForm' as const,
};

export const ROOT_ROUTES = {
  AUTH: 'Auth' as const,
  SETUP: 'Setup' as const,
  MAIN_STACK: 'MainStack' as const,
  SUSPENDED: 'Suspended' as const,
  BANNED: 'Banned' as const,
};
